"""Declarative base, metadata conventions, and the mixins every table draws from."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Index, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

# Deterministic constraint names. Postgres will happily invent names like
# "asset_tenant_id_fkey1"; Alembic cannot reliably drop what it cannot name, so
# every autogenerated downgrade would silently break. Fixing this after the schema
# ships means renaming every constraint in every deployed database.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """UUID primary keys, generated database-side by ``gen_random_uuid()``.

    UUIDs rather than bigserial because rows are created by API clients, offline
    mobile clients, and background workers that must mint identifiers before they
    can reach the database. ``gen_random_uuid()`` is core Postgres from 13 onward,
    so this needs no extension.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """Creation and modification instants, both maintained by the database.

    ``updated_at`` is refreshed by a trigger rather than by SQLAlchemy's ``onupdate``
    so that bulk updates, psql sessions, and Celery workers using raw SQL cannot
    leave a stale value behind. See ``touch_updated_at()`` in the initial migration.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class SoftDeleteMixin:
    """Tombstone column for entities an audit trail must still be able to reference.

    Every uniqueness constraint and lookup index on a soft-deletable table is partial
    (``WHERE deleted_at IS NULL``) so that deleting a tower frees its code for reuse
    without severing the audit log's reference to the original row.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)


class TenantScopedMixin:
    """Attaches a row to exactly one tenant, and is the column every RLS policy tests.

    ``ondelete="CASCADE"`` is intentional: deleting a tenant must remove its data
    rather than orphan it behind a policy that no longer matches anything.
    """

    @declared_attr
    @classmethod
    def tenant_id(cls) -> Mapped[uuid.UUID]:
        return mapped_column(
            PG_UUID(as_uuid=True),
            ForeignKey("tenant.id", ondelete="CASCADE"),
            nullable=False,
        )

    @declared_attr.directive
    @classmethod
    def __table_args__(cls) -> tuple[Index, ...]:
        # Nearly every query filters on tenant_id first; subclasses that need more
        # indexes override this and re-include the entry.
        return (Index(f"ix_{cls.__tablename__}_tenant_id", "tenant_id"),)
