"""Alembic environment.

Migrations connect as the schema owner (``OTGP_MIGRATION_DATABASE_URL``), never as the
unprivileged application role. The application role has no DDL rights, by design.
"""

from __future__ import annotations

from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool, text
from sqlalchemy.schema import SchemaItem

from alembic import context
from app.core.config import get_settings
from app.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Alembic drives DDL synchronously; strip the async driver from the URL.
config.set_main_option(
    "sqlalchemy.url",
    str(get_settings().migration_database_url).replace("+asyncpg", "+psycopg"),
)

target_metadata = Base.metadata

# Relations owned by a PostgreSQL extension, discovered at connect time. Autogenerate
# reflects everything on the search_path and would otherwise propose dropping every one
# of them.
#
# Enumerating them by name does not work. The postgis image's own init scripts install
# postgis_tiger_geocoder, whose tables (county, tabblock, place_lookup, …) land on the
# search_path; a Compose file that bind-mounts /docker-entrypoint-initdb.d replaces those
# scripts and never creates them. So the set differs between a developer's machine and
# CI, and any hard-coded list is wrong somewhere. Ask the catalogue instead.
_EXTENSION_OWNED: set[str] = set()

# Used in offline mode, where there is no connection to interrogate.
POSTGIS_OWNED = {
    "spatial_ref_sys",
    "geography_columns",
    "geometry_columns",
    "raster_columns",
    "raster_overviews",
}

# pg_depend records an 'e' dependency from every object an extension created back to the
# extension itself. This is exactly the question "did a human write this, or did CREATE
# EXTENSION?", and it is the only reliable way to ask it.
EXTENSION_OWNED_QUERY = text("""
    SELECT c.relname
    FROM pg_class c
    JOIN pg_depend d
      ON d.classid = 'pg_class'::regclass
     AND d.objid = c.oid
     AND d.deptype = 'e'
""")


def include_object(
    obj: SchemaItem,
    name: str | None,
    type_: str,
    reflected: bool,
    compare_to: SchemaItem | None,
) -> bool:
    """Keep objects this project does not own out of autogenerated migrations."""
    if name is not None and name in _EXTENSION_OWNED:
        return False
    if type_ == "table" and name in POSTGIS_OWNED:
        return False
    # GeoAlchemy2 emits its own spatial indexes; we declare ours explicitly on the
    # models, so reflected duplicates would produce spurious create/drop churn.
    is_geoalchemy_index = (
        type_ == "index" and reflected and name is not None and name.startswith("idx_")
    )
    return not is_geoalchemy_index


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        include_object=include_object,
        compare_type=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        _EXTENSION_OWNED.update(connection.scalars(EXTENSION_OWNED_QUERY))
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
