"""initial schema

Revision ID: 316a60e67311
Revises:
Create Date: 2026-07-10 18:11:01.991529
"""

from __future__ import annotations

import os
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# The unprivileged role the application connects as, created by
# deploy/postgres/init/01-app-role.sh. Row-Level Security is enforced only for it.
APP_ROLE = os.environ.get("APP_DB_USER", "otgp_app")

# Tables carrying tenant_id directly. Each gets a policy comparing that column against
# the transaction-local `otgp.tenant_id` setting.
TENANT_SCOPED_TABLES = (
    "user_account",
    "role",
    "project",
    "project_member",
    "asset",
)

# Tables with no tenant_id of their own. Their policies defer to a parent row whose own
# policy performs the tenant check, so isolation composes rather than being duplicated.
DERIVED_TABLES = {
    "tower": ("asset", "id"),
    "user_role": ("user_account", "user_id"),
    "role_permission": ("role", "role_id"),
}

# Tables whose updated_at is maintained by trigger rather than by the ORM, so that raw
# SQL, bulk updates and psql sessions cannot leave a stale value behind.
TOUCHED_TABLES = ("tenant", "role", "user_account", "project", "project_member", "asset")

# The permission catalogue. Global, not tenant-scoped: the set of things the software
# can do is a property of the software. Kept in step with app.core.permissions.ALL_PERMISSIONS
# by tests/test_permission_catalogue.py.
PERMISSIONS = (
    ("project:read", "View projects and their metadata"),
    ("project:write", "Create and modify projects"),
    ("project:delete", "Delete projects"),
    ("asset:read", "View network assets"),
    ("asset:write", "Create and modify network assets"),
    ("asset:delete", "Delete network assets"),
    ("member:read", "View project members"),
    ("member:write", "Add and remove project members"),
    ("role:read", "View roles and their permissions"),
    ("role:write", "Create and modify roles"),
    ("audit:read", "Read the audit log"),
)

# NULLIF guards the case where the setting exists but is the empty string, which
# `current_setting(..., true)` returns in some connection-pooler configurations.
_TENANT = "NULLIF(current_setting('otgp.tenant_id', true), '')::uuid"

revision: str = "316a60e67311"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permission")),
        sa.UniqueConstraint("code", name=op.f("uq_permission_code")),
    )
    op.create_table(
        "tenant",
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'",
            name=op.f("ck_tenant_slug_is_dns_label"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenant_slug")),
    )
    op.create_table(
        "role",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_role_tenant_id_tenant"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
        sa.UniqueConstraint("tenant_id", "name", name="uq_role_tenant_id_name"),
    )
    op.create_index("ix_role_tenant_id", "role", ["tenant_id"], unique=False)
    op.create_table(
        "user_account",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=True),
        sa.Column("full_name", sa.String(length=255), server_default=sa.text("''"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_tenant_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_user_account_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_account")),
        sa.UniqueConstraint("tenant_id", "email", name="uq_user_account_tenant_id_email"),
    )
    op.create_index("ix_user_account_tenant_id", "user_account", ["tenant_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("client_ip", postgresql.INET(), nullable=True),
        sa.Column(
            "user_agent", sa.String(length=512), server_default=sa.text("''"), nullable=False
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user_account.id"],
            name=op.f("fk_audit_log_actor_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_audit_log_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_entity_type_entity_id",
        "audit_log",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index("ix_audit_log_tenant_id", "audit_log", ["tenant_id"], unique=False)
    op.create_index(
        "ix_audit_log_tenant_id_occurred_at",
        "audit_log",
        ["tenant_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "project",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "area_of_interest",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("display_srid", sa.Integer(), server_default=sa.text("4326"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'",
            name=op.f("ck_project_slug_is_dns_label"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user_account.id"],
            name=op.f("fk_project_owner_id_user_account"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_project_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
    )
    op.create_index(
        "ix_project_area_of_interest",
        "project",
        ["area_of_interest"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index("ix_project_tenant_id", "project", ["tenant_id"], unique=False)
    op.create_index(
        "uq_project_tenant_id_slug",
        "project",
        ["tenant_id", "slug"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
            name=op.f("fk_role_permission_permission_id_permission"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
            name=op.f("fk_role_permission_role_id_role"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permission")),
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name=op.f("fk_user_role_role_id_role"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_user_role_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_role")),
    )
    op.create_table(
        "asset",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("asset_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("ground_elevation_m", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "in_construction",
                "active",
                "maintenance",
                "decommissioned",
                name="asset_status",
                native_enum=False,
                length=32,
            ),
            server_default=sa.text("'planned'"),
            nullable=False,
        ),
        sa.Column("vendor", sa.String(length=128), server_default=sa.text("''"), nullable=False),
        sa.Column("model", sa.String(length=128), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "serial_number", sa.String(length=128), server_default=sa.text("''"), nullable=False
        ),
        sa.Column("installed_at", sa.Date(), nullable=True),
        sa.Column("warranty_expires_at", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ground_elevation_m IS NULL OR ground_elevation_m BETWEEN -500 AND 9000",
            name=op.f("ck_asset_ground_elevation_within_earth_range"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_asset_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_asset_tenant_id_tenant"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset")),
    )
    op.create_index(
        "ix_asset_name_trgm",
        "asset",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_asset_project_id_asset_type", "asset", ["project_id", "asset_type"], unique=False
    )
    op.create_index("ix_asset_tenant_id", "asset", ["tenant_id"], unique=False)
    op.create_index(
        "ix_asset_tenant_id_location",
        "asset",
        ["tenant_id", "location"],
        unique=False,
        postgresql_using="gist",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_asset_project_id_code",
        "asset",
        ["project_id", "code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "project_member",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_project_member_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
            name=op.f("fk_project_member_role_id_role"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_project_member_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_project_member_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_member")),
        sa.UniqueConstraint(
            "project_id", "user_id", "role_id", name="uq_project_member_project_id_user_id_role_id"
        ),
    )
    op.create_index("ix_project_member_tenant_id", "project_member", ["tenant_id"], unique=False)
    op.create_index(
        "ix_project_member_user_id_project_id",
        "project_member",
        ["user_id", "project_id"],
        unique=False,
    )
    op.create_table(
        "tower",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("height_m", sa.Float(), nullable=False),
        sa.Column(
            "structure_type",
            sa.Enum(
                "lattice",
                "monopole",
                "guyed_mast",
                "rooftop",
                "water_tank",
                "camouflage",
                name="structure_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("max_load_kg", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "height_m > 0 AND height_m <= 700", name=op.f("ck_tower_height_is_physically_plausible")
        ),
        sa.CheckConstraint(
            "max_load_kg IS NULL OR max_load_kg > 0", name=op.f("ck_tower_max_load_is_positive")
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["asset.id"], name=op.f("fk_tower_id_asset"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tower")),
    )
    # ### end Alembic commands ###

    _create_touch_trigger()
    _enable_row_level_security()
    _enforce_append_only()
    _seed_permissions()


def _enforce_append_only() -> None:
    """Make UPDATE and DELETE on audit_log unavailable to the application role.

    A missing RLS policy does not deny an operation — it makes zero rows match, and the
    statement commits having changed nothing. Only a privilege revocation produces an
    error, which is what turns a tamper attempt into something monitoring can see.

    The role is granted UPDATE and DELETE by ``GRANT ... ON ALL TABLES`` and by
    ``ALTER DEFAULT PRIVILEGES`` in the init script, so this must run after the table
    exists. Guarded on the role existing, because a bare test database created without
    the init script must still be able to migrate.
    """
    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
                REVOKE UPDATE, DELETE, TRUNCATE ON audit_log FROM "{APP_ROLE}";
            END IF;
        END
        $$;
        """
    )


def _create_touch_trigger() -> None:
    """Maintain updated_at in the database, where nothing can route around it."""
    op.execute(
        """
        CREATE FUNCTION touch_updated_at() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$;
        """
    )
    for table in TOUCHED_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER {table}_touch_updated_at
                BEFORE UPDATE ON {table}
                FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
            """
        )


def _enable_row_level_security() -> None:
    """Enforce tenant isolation in Postgres rather than in application WHERE clauses.

    FORCE, not merely ENABLE: ENABLE exempts the table owner from its own policies, and
    the owner is exactly who runs migrations and, in many deployments, the application.
    FORCE subjects the owner too. Superusers and BYPASSRLS roles still bypass, which is
    why the application connects as a role holding neither.

    The tenant is read from a transaction-local setting. When unset, current_setting
    returns NULL, `tenant_id = NULL` is never true, and the query returns nothing. A
    forgotten tenant context is therefore an empty result, not a cross-tenant read.
    """
    for table in TENANT_SCOPED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
                USING (tenant_id = {_TENANT})
                WITH CHECK (tenant_id = {_TENANT});
            """
        )

    # Subtype and association tables: the EXISTS subquery reads a parent table that
    # carries its own policy, so the parent's tenant check applies transitively and the
    # predicate here needs no tenant_id of its own.
    for table, (parent, fk) in DERIVED_TABLES.items():
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        predicate = f"EXISTS (SELECT 1 FROM {parent} p WHERE p.id = {table}.{fk})"
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
                USING ({predicate})
                WITH CHECK ({predicate});
            """
        )

    # audit_log is append-only, enforced by two distinct mechanisms that are easy to
    # confuse:
    #
    #   * The RLS policies below restrict *which rows* a tenant may see and insert.
    #   * The REVOKE in _enforce_append_only() removes the UPDATE and DELETE *verbs*.
    #
    # Both are required. Omitting the REVOKE and relying on "no UPDATE policy means
    # denied" is wrong: Postgres does not raise, it simply matches zero rows, so the
    # UPDATE commits as a silent no-op and the caller cannot tell tampering was blocked.
    op.execute("ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE audit_log FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY audit_log_select ON audit_log FOR SELECT USING (tenant_id = {_TENANT})"
    )
    op.execute(
        f"CREATE POLICY audit_log_insert ON audit_log FOR INSERT WITH CHECK (tenant_id = {_TENANT})"
    )

    # `tenant` and `permission` carry no policy on purpose. A row in `tenant` defines a
    # tenant rather than belonging to one, and `permission` is a global catalogue. Both
    # are readable by any authenticated session; neither exposes another tenant's data.


def _seed_permissions() -> None:
    op.bulk_insert(
        sa.table(
            "permission",
            sa.column("code", sa.String),
            sa.column("description", sa.Text),
        ),
        [{"code": code, "description": description} for code, description in PERMISSIONS],
    )


def downgrade() -> None:
    for table in TOUCHED_TABLES:
        op.execute(f"DROP TRIGGER {table}_touch_updated_at ON {table}")
    op.execute("DROP FUNCTION touch_updated_at()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tower")
    op.drop_index("ix_project_member_user_id_project_id", table_name="project_member")
    op.drop_index("ix_project_member_tenant_id", table_name="project_member")
    op.drop_table("project_member")
    op.drop_index(
        "uq_asset_project_id_code",
        table_name="asset",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_asset_tenant_id_location",
        table_name="asset",
        postgresql_using="gist",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_asset_tenant_id", table_name="asset")
    op.drop_index("ix_asset_project_id_asset_type", table_name="asset")
    op.drop_index(
        "ix_asset_name_trgm",
        table_name="asset",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("asset")
    op.drop_table("user_role")
    op.drop_table("role_permission")
    op.drop_index(
        "uq_project_tenant_id_slug",
        table_name="project",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_project_tenant_id", table_name="project")
    op.drop_index("ix_project_area_of_interest", table_name="project", postgresql_using="gist")
    op.drop_table("project")
    op.drop_index("ix_audit_log_tenant_id_occurred_at", table_name="audit_log")
    op.drop_index("ix_audit_log_tenant_id", table_name="audit_log")
    op.drop_index("ix_audit_log_entity_type_entity_id", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("ix_user_account_tenant_id", table_name="user_account")
    op.drop_table("user_account")
    op.drop_index("ix_role_tenant_id", table_name="role")
    op.drop_table("role")
    op.drop_table("tenant")
    op.drop_table("permission")
    # ### end Alembic commands ###
